DROP DATABASE IF EXISTS PROWAD;
CREATE DATABASE PROWAD;
USE PROWAD;
CREATE TABLE Atributo (id int(10) NOT NULL AUTO_INCREMENT, nombre varchar(255) NOT NULL, TipoDatoid int(10), PRIMARY KEY (id));
CREATE TABLE Carrito (id int(10) NOT NULL AUTO_INCREMENT, fechaCompra date, Usuariocurp varchar(255), Estadoid int(10), PRIMARY KEY (id));
CREATE TABLE Categoria (id int(10) NOT NULL AUTO_INCREMENT, nombre varchar(255) NOT NULL UNIQUE, PRIMARY KEY (id));
CREATE TABLE Categoria_Atributo (Atributoid int(10) NOT NULL, Categoriaid int(10) NOT NULL, PRIMARY KEY (Atributoid, Categoriaid));
CREATE TABLE Estado (id int(10) NOT NULL AUTO_INCREMENT, nombre varchar(255) NOT NULL UNIQUE, PRIMARY KEY (id));
CREATE TABLE Producto (id int(10) NOT NULL AUTO_INCREMENT, nombre varchar(255) NOT NULL UNIQUE, Tiendaid int(10), PRIMARY KEY (id));
CREATE TABLE Producto_Atributo (Productoid int(10) NOT NULL, Atributoid int(10) NOT NULL, valorCadena varchar(255), valorEntero int(10), valorFecha date, valorFlotante double, PRIMARY KEY (Productoid, Atributoid));
CREATE TABLE Producto_Carrito (Productoid int(10) NOT NULL, Carritoid int(10) NOT NULL, PRIMARY KEY (Productoid, Carritoid));
CREATE TABLE Producto_Categoria (Productoid int(10) NOT NULL, Categoriaid int(10) NOT NULL, PRIMARY KEY (Productoid, Categoriaid));
CREATE TABLE Rol (id int(10) NOT NULL AUTO_INCREMENT, nombre varchar(255) NOT NULL UNIQUE, PRIMARY KEY (id));
CREATE TABLE Tienda (id int(10) NOT NULL AUTO_INCREMENT, nombre varchar(255) NOT NULL UNIQUE, PRIMARY KEY (id));
CREATE TABLE TipoDato (id int(10) NOT NULL AUTO_INCREMENT, nombre varchar(255) NOT NULL UNIQUE, PRIMARY KEY (id));
CREATE TABLE Usuario (curp varchar(255) NOT NULL, nombre varchar(255) NOT NULL, primerApellido varchar(255) NOT NULL, segundoApellido varchar(255), correoElectronico varchar(255) NOT NULL, contrasena varchar(255) NOT NULL, Tiendaid int(10), Rolid int(10), PRIMARY KEY (curp));
ALTER TABLE Producto ADD INDEX FKProducto152303 (Tiendaid), ADD CONSTRAINT FKProducto152303 FOREIGN KEY (Tiendaid) REFERENCES Tienda (id);
ALTER TABLE Producto_Atributo ADD INDEX FKProducto_A715530 (Productoid), ADD CONSTRAINT FKProducto_A715530 FOREIGN KEY (Productoid) REFERENCES Producto (id);
ALTER TABLE Producto_Atributo ADD INDEX FKProducto_A807320 (Atributoid), ADD CONSTRAINT FKProducto_A807320 FOREIGN KEY (Atributoid) REFERENCES Atributo (id);
ALTER TABLE Categoria_Atributo ADD INDEX FKCategoria_432270 (Categoriaid), ADD CONSTRAINT FKCategoria_432270 FOREIGN KEY (Categoriaid) REFERENCES Categoria (id);
ALTER TABLE Categoria_Atributo ADD INDEX FKCategoria_12577 (Atributoid), ADD CONSTRAINT FKCategoria_12577 FOREIGN KEY (Atributoid) REFERENCES Atributo (id);
ALTER TABLE Atributo ADD INDEX FKAtributo156815 (TipoDatoid), ADD CONSTRAINT FKAtributo156815 FOREIGN KEY (TipoDatoid) REFERENCES TipoDato (id);
ALTER TABLE Usuario ADD INDEX FKUsuario775877 (Tiendaid), ADD CONSTRAINT FKUsuario775877 FOREIGN KEY (Tiendaid) REFERENCES Tienda (id);
ALTER TABLE Carrito ADD INDEX FKCarrito608320 (Usuariocurp), ADD CONSTRAINT FKCarrito608320 FOREIGN KEY (Usuariocurp) REFERENCES Usuario (curp);
ALTER TABLE Usuario ADD INDEX FKUsuario38509 (Rolid), ADD CONSTRAINT FKUsuario38509 FOREIGN KEY (Rolid) REFERENCES Rol (id);
ALTER TABLE Carrito ADD INDEX FKCarrito561085 (Estadoid), ADD CONSTRAINT FKCarrito561085 FOREIGN KEY (Estadoid) REFERENCES Estado (id);
ALTER TABLE Producto_Categoria ADD INDEX FKProducto_C337301 (Productoid), ADD CONSTRAINT FKProducto_C337301 FOREIGN KEY (Productoid) REFERENCES Producto (id);
ALTER TABLE Producto_Categoria ADD INDEX FKProducto_C690358 (Categoriaid), ADD CONSTRAINT FKProducto_C690358 FOREIGN KEY (Categoriaid) REFERENCES Categoria (id);
ALTER TABLE Producto_Carrito ADD INDEX FKProducto_C410467 (Productoid), ADD CONSTRAINT FKProducto_C410467 FOREIGN KEY (Productoid) REFERENCES Producto (id);
ALTER TABLE Producto_Carrito ADD INDEX FKProducto_C940586 (Carritoid), ADD CONSTRAINT FKProducto_C940586 FOREIGN KEY (Carritoid) REFERENCES Carrito (id);
