package mx.prowad.model;

// Generated 01-sep-2015 17:22:12 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Carrito generated by hbm2java
 */
@Entity
@Table(name = "Carrito", catalog = "PROWAD")
public class Carrito implements java.io.Serializable {

	private Integer id;
	private Date fechaCompra;
	private Estado estado;
	private Usuario usuario;
	private Set<ProductoCarrito> productosCarrito = new HashSet<ProductoCarrito>(0);

	public Carrito() {
	}

	public Carrito(Usuario usuario, Estado estado) {
		this.usuario = usuario;
		this.estado = estado;
	}

	public Carrito(Usuario usuario, Date fechaCompra, Estado estado) {
		this.usuario = usuario;
		this.fechaCompra = fechaCompra;
		this.estado = estado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FechaCompra", length = 10)
	public Date getFechaCompra() {
		return this.fechaCompra;
	}

	public void setFechaCompra(Date fechaCompra) {
		this.fechaCompra = fechaCompra;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Estadoid", referencedColumnName = "id")
	public Estado getEstado() {
		return estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "id.carrito", cascade = CascadeType.ALL)
	public Set<ProductoCarrito> getProductosCarrito() {
		return productosCarrito;
	}

	public void setProductosCarrito(Set<ProductoCarrito> productosAtributo) {
		this.productosCarrito = productosAtributo;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Usuariocurp", referencedColumnName = "curp")
	public Usuario getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}
	
	

}
