package mx.prowad.model;

// Generated 01-sep-2015 17:22:12 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.OneToMany;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name = "Categoria", catalog = "PROWAD", uniqueConstraints = @UniqueConstraint(columnNames = "nombre"))
public class Categoria implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private Set<CategoriaAtributo> categoriasAtributo = new HashSet<CategoriaAtributo>(0);

	public Categoria() {
	}

	public Categoria(String nombre) {
		this.nombre = nombre;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", unique = true, nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "id.categoria", cascade = CascadeType.ALL)
	public Set<CategoriaAtributo> getCategoriasAtributo() {
		return categoriasAtributo;
	}

	public void setCategoriasAtributo(Set<CategoriaAtributo> categoriasAtributo) {
		this.categoriasAtributo = categoriasAtributo;
	}

	
	
	

}
