package mx.prowad.model;

// Generated 01-sep-2015 17:22:12 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProductoCarrito generated by hbm2java
 */
@Entity
@Table(name = "Producto_Carrito", catalog = "PROWAD")
public class ProductoCarrito implements java.io.Serializable {

	private ProductoCarritoId id;
	private int cantidad;

	public ProductoCarrito() {
	}

	public ProductoCarrito(ProductoCarritoId id, int cantidad) {
		this.id = id;
		this.cantidad = cantidad;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "productoid", column = @Column(name = "Productoid", nullable = false)),
			@AttributeOverride(name = "carritoid", column = @Column(name = "Carritoid", nullable = false)) })
	public ProductoCarritoId getId() {
		return this.id;
	}

	public void setId(ProductoCarritoId id) {
		this.id = id;
	}

	@Column(name = "cantidad", nullable = false)
	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

}
