package mx.prowad.model;

// Generated 01-sep-2015 17:22:12 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductoCategoriaId generated by hbm2java
 */
@Embeddable
public class ProductoCategoriaId implements java.io.Serializable {

	private int productoid;
	private int categoriaid;

	public ProductoCategoriaId() {
	}

	public ProductoCategoriaId(int productoid, int categoriaid) {
		this.productoid = productoid;
		this.categoriaid = categoriaid;
	}

	@Column(name = "Productoid", nullable = false)
	public int getProductoid() {
		return this.productoid;
	}

	public void setProductoid(int productoid) {
		this.productoid = productoid;
	}

	@Column(name = "Categoriaid", nullable = false)
	public int getCategoriaid() {
		return this.categoriaid;
	}

	public void setCategoriaid(int categoriaid) {
		this.categoriaid = categoriaid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductoCategoriaId))
			return false;
		ProductoCategoriaId castOther = (ProductoCategoriaId) other;

		return (this.getProductoid() == castOther.getProductoid())
				&& (this.getCategoriaid() == castOther.getCategoriaid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProductoid();
		result = 37 * result + this.getCategoriaid();
		return result;
	}

}
