package mx.prowad.model;

// Generated 01-sep-2015 17:22:12 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "Producto", catalog = "PROWAD")
public class Producto implements java.io.Serializable {

	private Integer id;
	private Tienda tienda;
	private String nombre;
	private Double precio;
	private Integer cantidad;
	private Set<ProductoCategoria> productosCategoria = new HashSet<ProductoCategoria>(0);
	private Set<ProductoAtributo> productosAtributo = new HashSet<ProductoAtributo>(0);
	
	public Producto() {
	}

	public Producto(Tienda tienda, String nombre) {
		this.tienda = tienda;
		this.nombre = nombre;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "id.producto", cascade = CascadeType.ALL)
	public Set<ProductoCategoria> getProductosCategoria() {
		return productosCategoria;
	}

	public void setProductosCategoria(Set<ProductoCategoria> productosCategoria) {
		this.productosCategoria = productosCategoria;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Tiendaid", referencedColumnName = "id")
	public Tienda getTienda() {
		return tienda;
	}

	public void setTienda(Tienda tienda) {
		this.tienda = tienda;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "id.producto", cascade = CascadeType.ALL)
	public Set<ProductoAtributo> getProductosAtributo() {
		return productosAtributo;
	}

	public void setProductosAtributo(Set<ProductoAtributo> productosAtributo) {
		this.productosAtributo = productosAtributo;
	}
	
	@Column(name = "precio", precision = 22, scale = 0)
	public Double getPrecio() {
		return this.precio;
	}

	public void setPrecio(Double precio) {
		this.precio = precio;
	}

	@Column(name = "cantidad")
	public Integer getCantidad() {
		return cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}
	
	

}
