package mx.prowad.model;

// Generated 01-sep-2015 17:22:12 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "Producto", catalog = "PROWAD")
public class Producto implements java.io.Serializable {

	private Integer id;
	private int tiendaid;
	private String nombre;
	private int cantidad;

	public Producto() {
	}

	public Producto(int tiendaid, String nombre, int cantidad) {
		this.tiendaid = tiendaid;
		this.nombre = nombre;
		this.cantidad = cantidad;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Tiendaid", nullable = false)
	public int getTiendaid() {
		return this.tiendaid;
	}

	public void setTiendaid(int tiendaid) {
		this.tiendaid = tiendaid;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "cantidad", nullable = false)
	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

}
