package mx.prowad.model;

// Generated 01-sep-2015 17:22:12 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * ProductoAtributoId generated by hbm2java
 */
@Embeddable
public class ProductoAtributoId implements java.io.Serializable {

	private Producto producto;
	private Atributo atributo;

	public ProductoAtributoId() {
	}

	public ProductoAtributoId(Producto producto, Atributo atributo) {
		this.producto = producto;
		this.atributo = atributo;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Productoid", referencedColumnName = "id")
	public Producto getProducto() {
		return producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Atributoid", referencedColumnName = "id")
	public Atributo getAtributo() {
		return atributo;
	}

	public void setAtributo(Atributo atributo) {
		this.atributo = atributo;
	}

	
}
