package mx.prowad.model;

// Generated 01-sep-2015 17:22:12 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * ProductoCarritoId generated by hbm2java
 */
@Embeddable
public class ProductoCarritoId implements java.io.Serializable {

	private Producto producto;
	private Carrito carrito;

	public ProductoCarritoId() {
	}

	public ProductoCarritoId(Producto producto, Carrito carrito) {
		this.producto = producto;
		this.carrito = carrito;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Productoid", referencedColumnName = "id")
	public Producto getProducto() {
		return producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Carritoid", referencedColumnName = "id")
	public Carrito getCarrito() {
		return carrito;
	}

	public void setCarrito(Carrito carrito) {
		this.carrito = carrito;
	}

	
}
