package mx.prowad.model;

// Generated 01-sep-2015 17:22:12 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductoAtributo generated by hbm2java
 */
@Entity
@Table(name = "Producto_Atributo", catalog = "PROWAD")
public class ProductoAtributo implements java.io.Serializable {

	private ProductoAtributoId id;
	private String valorCadena;
	private Integer valorEntero;
	private Date valorFecha;
	private Double valorFlotante;
	private int tipoDatoid;

	public ProductoAtributo() {
	}

	public ProductoAtributo(ProductoAtributoId id, int tipoDatoid) {
		this.id = id;
		this.tipoDatoid = tipoDatoid;
	}

	public ProductoAtributo(ProductoAtributoId id, String valorCadena,
			Integer valorEntero, Date valorFecha, Double valorFlotante,
			int tipoDatoid) {
		this.id = id;
		this.valorCadena = valorCadena;
		this.valorEntero = valorEntero;
		this.valorFecha = valorFecha;
		this.valorFlotante = valorFlotante;
		this.tipoDatoid = tipoDatoid;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "productoid", column = @Column(name = "Productoid", nullable = false)),
			@AttributeOverride(name = "atributoid", column = @Column(name = "Atributoid", nullable = false)) })
	public ProductoAtributoId getId() {
		return this.id;
	}

	public void setId(ProductoAtributoId id) {
		this.id = id;
	}

	@Column(name = "valorCadena")
	public String getValorCadena() {
		return this.valorCadena;
	}

	public void setValorCadena(String valorCadena) {
		this.valorCadena = valorCadena;
	}

	@Column(name = "valorEntero")
	public Integer getValorEntero() {
		return this.valorEntero;
	}

	public void setValorEntero(Integer valorEntero) {
		this.valorEntero = valorEntero;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "valorFecha", length = 10)
	public Date getValorFecha() {
		return this.valorFecha;
	}

	public void setValorFecha(Date valorFecha) {
		this.valorFecha = valorFecha;
	}

	@Column(name = "valorFlotante", precision = 22, scale = 0)
	public Double getValorFlotante() {
		return this.valorFlotante;
	}

	public void setValorFlotante(Double valorFlotante) {
		this.valorFlotante = valorFlotante;
	}

	@Column(name = "TipoDatoid", nullable = false)
	public int getTipoDatoid() {
		return this.tipoDatoid;
	}

	public void setTipoDatoid(int tipoDatoid) {
		this.tipoDatoid = tipoDatoid;
	}

}
