package mx.prowad.model;

// Generated 01-sep-2015 17:22:12 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductoAtributoId generated by hbm2java
 */
@Embeddable
public class ProductoAtributoId implements java.io.Serializable {

	private int productoid;
	private int atributoid;

	public ProductoAtributoId() {
	}

	public ProductoAtributoId(int productoid, int atributoid) {
		this.productoid = productoid;
		this.atributoid = atributoid;
	}

	@Column(name = "Productoid", nullable = false)
	public int getProductoid() {
		return this.productoid;
	}

	public void setProductoid(int productoid) {
		this.productoid = productoid;
	}

	@Column(name = "Atributoid", nullable = false)
	public int getAtributoid() {
		return this.atributoid;
	}

	public void setAtributoid(int atributoid) {
		this.atributoid = atributoid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductoAtributoId))
			return false;
		ProductoAtributoId castOther = (ProductoAtributoId) other;

		return (this.getProductoid() == castOther.getProductoid())
				&& (this.getAtributoid() == castOther.getAtributoid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProductoid();
		result = 37 * result + this.getAtributoid();
		return result;
	}

}
