package mx.prowad.model;

// Generated 01-sep-2015 17:22:12 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * ProductoCategoriaId generated by hbm2java
 */
@Embeddable
public class ProductoCategoriaId implements java.io.Serializable {

	private Producto producto;
	private Categoria categoria;

	public ProductoCategoriaId() {
	}

	public ProductoCategoriaId(Producto producto, Categoria categoria) {
		this.producto = producto;
		this.categoria = categoria;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Productoid", referencedColumnName = "id")
	public Producto getProducto() {
		return producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Categoriaid", referencedColumnName = "id")
	public Categoria getCategoria() {
		return categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	
}
