package mx.prowad.model;

// Generated 01-sep-2015 17:22:12 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "Usuario", catalog = "PROWAD")
public class Usuario implements java.io.Serializable {

	private String curp;
	private int tiendaid;
	private String nombre;
	private String primerApellido;
	private String segundoApellido;
	private String correoElectronico;
	private String contrasena;
	private int rolid;

	public Usuario() {
	}

	public Usuario(String curp, int tiendaid, String nombre,
			String primerApellido, String correoElectronico, String contrasena,
			int rolid) {
		this.curp = curp;
		this.tiendaid = tiendaid;
		this.nombre = nombre;
		this.primerApellido = primerApellido;
		this.correoElectronico = correoElectronico;
		this.contrasena = contrasena;
		this.rolid = rolid;
	}

	public Usuario(String curp, int tiendaid, String nombre,
			String primerApellido, String segundoApellido,
			String correoElectronico, String contrasena, int rolid) {
		this.curp = curp;
		this.tiendaid = tiendaid;
		this.nombre = nombre;
		this.primerApellido = primerApellido;
		this.segundoApellido = segundoApellido;
		this.correoElectronico = correoElectronico;
		this.contrasena = contrasena;
		this.rolid = rolid;
	}

	@Id
	@Column(name = "curp", unique = true, nullable = false, length = 18)
	public String getCurp() {
		return this.curp;
	}

	public void setCurp(String curp) {
		this.curp = curp;
	}

	@Column(name = "Tiendaid", nullable = false)
	public int getTiendaid() {
		return this.tiendaid;
	}

	public void setTiendaid(int tiendaid) {
		this.tiendaid = tiendaid;
	}

	@Column(name = "Nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "PrimerApellido", nullable = false, length = 50)
	public String getPrimerApellido() {
		return this.primerApellido;
	}

	public void setPrimerApellido(String primerApellido) {
		this.primerApellido = primerApellido;
	}

	@Column(name = "SegundoApellido", length = 50)
	public String getSegundoApellido() {
		return this.segundoApellido;
	}

	public void setSegundoApellido(String segundoApellido) {
		this.segundoApellido = segundoApellido;
	}

	@Column(name = "CorreoElectronico", nullable = false, length = 50)
	public String getCorreoElectronico() {
		return this.correoElectronico;
	}

	public void setCorreoElectronico(String correoElectronico) {
		this.correoElectronico = correoElectronico;
	}

	@Column(name = "Contrasena", nullable = false, length = 20)
	public String getContrasena() {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

	@Column(name = "Rolid", nullable = false)
	public int getRolid() {
		return this.rolid;
	}

	public void setRolid(int rolid) {
		this.rolid = rolid;
	}

}
